name: auth_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.2.3
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  injectable: ^2.1.0


dev_dependencies:
  flutter_lints: ^2.0.0


